#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.15
# from Racc grammer file "".
#

require 'racc/parser.rb'


# Clases requeridas
require_relative 'lexer'
require_relative 'clasesGusb'

# Errores sintacticos
class ErrorSintactico < RuntimeError

	def initialize(token)
		@token = token
	end

	def to_s
		"ERROR: fila: " + @token.fila.to_s() + ", columna: " + @token.columna.to_s() + ", token inesperado: #{@token.token} \n"   # EL PROBLEMA ES ACA
	end
end

# Main del Parser
class ParserGusb < Racc::Parser

module_eval(<<'...end parserGusb2.y/module_eval...', 'parserGusb2.y', 228)
	
	def initialize(tokens)
		@tokens = tokens
		@yydebug = true
		super()
	end 

	def parse
		do_parse
	end

	def next_token
		@tokens.shift
	end

	def on_error(id, token, pila)
		raise ErrorSintactico.new(token)
	end
...end parserGusb2.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     9,    63,    92,    28,    28,    28,    59,    60,     9,    72,
    73,    74,    70,    71,    82,    81,    83,    80,    78,    79,
     2,    76,    17,    91,     6,   136,   136,   136,    90,    88,
    17,    69,    65,   128,   127,     9,    97,    98,    99,    14,
     9,    16,    92,    18,    19,    20,     9,    14,    21,    16,
    93,    18,    19,    20,    28,     9,    21,    17,     5,     6,
     9,    97,    98,    99,    72,    73,    74,     9,    17,    68,
     9,    72,    73,    74,    14,    43,    16,    29,    18,    19,
    20,    28,    17,    21,     9,    14,   144,    16,    67,    18,
    19,    20,    17,    23,    21,     9,    22,    43,    65,    14,
     3,    16,   151,    18,    19,    20,     9,   152,    21,    14,
     9,    16,    66,    18,    19,    20,   155,    17,    21,   156,
    58,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    17,   nil,
     6,   nil,   nil,   nil,    14,   nil,    16,   nil,    18,    19,
    20,   nil,   nil,    21,   nil,    14,   nil,    16,   nil,    18,
    19,    20,   nil,   nil,    21,    72,    73,    74,    70,    71,
    82,    81,    83,    80,    78,    79,   nil,    76,    77,   nil,
    75,    72,    73,    74,    70,    71,    82,    81,    83,    80,
    78,    79,   nil,    76,    77,   nil,    75,   nil,    72,    73,
    74,    70,    71,    82,    81,    83,    80,    78,    79,   138,
    76,    77,   nil,    75,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   147,    72,    73,    74,    70,    71,    82,    81,    83,
    80,    78,    79,   nil,    76,    77,   nil,    75,    84,    54,
    43,     9,   nil,   nil,   nil,    40,   nil,    54,    43,     9,
   nil,    39,   nil,    40,   nil,   nil,   nil,   nil,   nil,    39,
   nil,   nil,   146,    72,    73,    74,    70,    71,   -74,   -74,
   -74,   -74,    33,    38,   nil,    34,    35,    36,    44,    45,
    33,    38,   nil,    34,    35,    36,    44,    45,    72,    73,
    74,    70,    71,    82,    81,    83,    80,    78,    79,   nil,
    76,    77,   nil,    75,    54,    43,     9,   nil,   nil,   nil,
    40,   nil,   nil,    43,     9,   nil,    39,   nil,    40,   nil,
   nil,    43,     9,   nil,    39,   nil,    40,   nil,    89,   nil,
   nil,   nil,    39,   nil,   nil,   nil,   nil,    33,    38,   nil,
    34,    35,    36,    44,    45,    33,    38,   nil,    34,    35,
    36,    44,    45,    33,    38,   nil,    34,    35,    36,    44,
    45,    43,     9,   nil,   nil,   nil,    40,   nil,   nil,    43,
     9,   nil,    39,   nil,    40,   nil,   nil,    43,     9,   nil,
    39,   nil,    40,   nil,   nil,   nil,   nil,   nil,    39,   nil,
   nil,   nil,   nil,    33,    38,   nil,    34,    35,    36,    44,
    45,    33,    38,   nil,    34,    35,    36,    44,    45,    33,
    38,   nil,    34,    35,    36,    44,    45,    43,     9,   nil,
   nil,   nil,    40,   nil,   nil,    43,     9,   nil,    39,   nil,
    40,   nil,   nil,    43,     9,   nil,    39,   nil,    40,   nil,
   nil,   nil,   nil,   nil,    39,   nil,   nil,   nil,   nil,    33,
    38,   nil,    34,    35,    36,    44,    45,    33,    38,   nil,
    34,    35,    36,    44,    45,    33,    38,   nil,    34,    35,
    36,    44,    45,    43,     9,   nil,   nil,   nil,    40,   nil,
   nil,    43,     9,   nil,    39,   nil,    40,   nil,   nil,    43,
     9,   nil,    39,   nil,    40,   nil,   nil,   nil,   nil,   nil,
    39,   nil,   nil,   nil,   nil,    33,    38,   nil,    34,    35,
    36,    44,    45,    33,    38,   nil,    34,    35,    36,    44,
    45,    33,    38,   nil,    34,    35,    36,    44,    45,    43,
     9,   nil,   nil,   nil,    40,   nil,   nil,    43,     9,   nil,
    39,   nil,    40,   nil,   nil,    43,     9,   nil,    39,   nil,
    40,   nil,   nil,   nil,   nil,   nil,    39,   nil,   nil,   nil,
   nil,    33,    38,   nil,    34,    35,    36,    44,    45,    33,
    38,   nil,    34,    35,    36,    44,    45,    33,    38,   nil,
    34,    35,    36,    44,    45,    43,     9,   nil,   nil,   nil,
    40,   nil,   nil,    43,     9,   nil,    39,   nil,    40,   nil,
   nil,    43,     9,   nil,    39,   nil,    40,   nil,   nil,   nil,
   nil,   nil,    39,   nil,   nil,   nil,   nil,    33,    38,   nil,
    34,    35,    36,    44,    45,    33,    38,   nil,    34,    35,
    36,    44,    45,    33,    38,   nil,    34,    35,    36,    44,
    45,    43,     9,   nil,   nil,   nil,    40,   nil,   nil,    43,
     9,   nil,    39,   nil,    40,   nil,   nil,    43,     9,   nil,
    39,   nil,    40,   nil,   nil,   nil,   nil,   nil,    39,   nil,
   nil,   nil,   nil,    33,    38,   nil,    34,    35,    36,    44,
    45,    33,    38,   nil,    34,    35,    36,    44,    45,    33,
    38,   nil,    34,    35,    36,    44,    45,    43,     9,   nil,
   nil,   nil,    40,   nil,   nil,    43,     9,   nil,    39,   nil,
    40,   nil,   nil,    43,     9,   nil,    39,   nil,    40,   nil,
   nil,   nil,   nil,   nil,    39,   nil,   nil,   nil,   nil,    33,
    38,   nil,    34,    35,    36,    44,    45,    33,    38,   nil,
    34,    35,    36,    44,    45,    33,    38,   nil,    34,    35,
    36,    44,    45,    43,     9,   nil,   nil,   nil,    40,   nil,
   nil,    43,     9,   nil,    39,   nil,    40,   nil,   nil,    43,
     9,   nil,    39,   nil,    40,   nil,   nil,   nil,   nil,   nil,
    39,   nil,   nil,   nil,   nil,    33,    38,   nil,    34,    35,
    36,    44,    45,    33,    38,   nil,    34,    35,    36,    44,
    45,    33,    38,   nil,    34,    35,    36,    44,    45,    43,
     9,   nil,   nil,   nil,    40,   nil,   nil,    43,     9,   nil,
    39,   nil,    40,   nil,   nil,    43,     9,   nil,    39,   nil,
    40,   nil,   nil,   nil,   nil,   nil,    39,   nil,   nil,   nil,
   nil,    33,    38,   nil,    34,    35,    36,    44,    45,    33,
    38,   nil,    34,    35,    36,    44,    45,    33,    38,   nil,
    34,    35,    36,    44,    45,    43,     9,   nil,   nil,   nil,
    40,   nil,   nil,   nil,   nil,   nil,    39,   nil,    72,    73,
    74,    70,    71,    82,    81,    83,    80,    78,    79,   nil,
    76,    77,   nil,    75,   nil,   nil,   nil,    33,    38,   nil,
    34,    35,    36,    44,    45,   145,    72,    73,    74,    70,
    71,    82,    81,    83,    80,    78,    79,   nil,    76,    77,
   nil,    75,    72,    73,    74,    70,    71,    82,    81,    83,
    80,    78,    79,   131,    76,    77,   nil,    75,    72,    73,
    74,    70,    71,    82,    81,    83,    80,    78,    79,   132,
    76,    77,   nil,    75,    72,    73,    74,    70,    71,    82,
    81,    83,    80,    78,    79,   133,    76,    77,   nil,    75,
    72,    73,    74,    70,    71,    82,    81,    83,    80,    78,
    79,   134,    76,    77,   nil,    75,    72,    73,    74,    70,
    71,   -74,   -74,   -74,   -74,   129,   nil,   122,    72,    73,
    74,    70,    71,    82,    81,    83,    80,    78,    79,   nil,
    76,    77,   nil,    75,    72,    73,    74,    70,    71,    82,
    81,    83,    80,    78,    79,   nil,    76,    77,   130,    75,
    72,    73,    74,    70,    71,    82,    81,    83,    80,    78,
    79,   nil,    76,    77,   nil,    75,    72,    73,    74,    70,
    71,    82,    81,    83,    80,    78,    79,   nil,    76,    77,
   nil,    75,    72,    73,    74,    70,    71,    82,    81,    83,
    80,    78,    79,   nil,    76,    77,   nil,    75,    72,    73,
    74,    70,    71,    82,    81,    83,    80,    78,    79,   nil,
    76,    77,    72,    73,    74,    70,    71,    82,    81,    83,
    80,   -74,   -74,    72,    73,    74,    70,    71,    82,    81,
    83,    80,   -74,   -74,    72,    73,    74,    70,    71,    82,
    81,    83,    80,    78,    79,    72,    73,    74,    70,    71,
   -74,   -74,   -74,   -74,    72,    73,    74,    70,    71,   -74,
   -74,   -74,   -74 ]

racc_action_check = [
   151,    31,    55,   150,   123,   121,    26,    26,   146,   114,
   114,   114,   114,   114,   114,   114,   114,   114,   114,   114,
     0,   114,   151,    49,   151,   150,   123,   121,    48,    46,
   146,    36,    31,    99,    95,     2,    59,    59,    59,   151,
    21,   151,    52,   151,   151,   151,    84,   146,   151,   146,
    56,   146,   146,   146,    57,    58,   146,     2,     2,     2,
    89,   127,   127,   127,   108,   108,   108,    18,    84,    35,
    28,   107,   107,   107,     2,   128,     2,     8,     2,     2,
     2,     7,    89,     2,     6,    84,   140,    84,    34,    84,
    84,    84,    28,     4,    84,    24,     3,   144,   145,    89,
     1,    89,   147,    89,    89,    89,    17,   148,    89,    28,
    60,    28,    33,    28,    28,    28,   154,    24,    28,   155,
    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    17,   nil,
    17,   nil,   nil,   nil,    24,   nil,    24,   nil,    24,    24,
    24,   nil,   nil,    24,   nil,    17,   nil,    17,   nil,    17,
    17,    17,   nil,   nil,    17,   126,   126,   126,   126,   126,
   126,   126,   126,   126,   126,   126,   nil,   126,   126,   nil,
   126,   143,   143,   143,   143,   143,   143,   143,   143,   143,
   143,   143,   nil,   143,   143,   nil,   143,   nil,    37,    37,
    37,    37,    37,    37,    37,    37,    37,    37,    37,   126,
    37,    37,   nil,    37,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   143,   142,   142,   142,   142,   142,   142,   142,   142,
   142,   142,   142,   nil,   142,   142,   nil,   142,    37,    19,
    19,    19,   nil,   nil,   nil,    19,   nil,    20,    20,    20,
   nil,    19,   nil,    20,   nil,   nil,   nil,   nil,   nil,    20,
   nil,   nil,   142,   117,   117,   117,   117,   117,   117,   117,
   117,   117,    19,    19,   nil,    19,    19,    19,    19,    19,
    20,    20,   nil,    20,    20,    20,    20,    20,    47,    47,
    47,    47,    47,    47,    47,    47,    47,    47,    47,   nil,
    47,    47,   nil,    47,    92,    92,    92,   nil,   nil,   nil,
    92,   nil,   nil,   136,   136,   nil,    92,   nil,   136,   nil,
   nil,   138,   138,   nil,   136,   nil,   138,   nil,    47,   nil,
   nil,   nil,   138,   nil,   nil,   nil,   nil,    92,    92,   nil,
    92,    92,    92,    92,    92,   136,   136,   nil,   136,   136,
   136,   136,   136,   138,   138,   nil,   138,   138,   138,   138,
   138,    29,    29,   nil,   nil,   nil,    29,   nil,   nil,    93,
    93,   nil,    29,   nil,    93,   nil,   nil,   130,   130,   nil,
    93,   nil,   130,   nil,   nil,   nil,   nil,   nil,   130,   nil,
   nil,   nil,   nil,    29,    29,   nil,    29,    29,    29,    29,
    29,    93,    93,   nil,    93,    93,    93,    93,    93,   130,
   130,   nil,   130,   130,   130,   130,   130,    83,    83,   nil,
   nil,   nil,    83,   nil,   nil,    82,    82,   nil,    83,   nil,
    82,   nil,   nil,    81,    81,   nil,    82,   nil,    81,   nil,
   nil,   nil,   nil,   nil,    81,   nil,   nil,   nil,   nil,    83,
    83,   nil,    83,    83,    83,    83,    83,    82,    82,   nil,
    82,    82,    82,    82,    82,    81,    81,   nil,    81,    81,
    81,    81,    81,    16,    16,   nil,   nil,   nil,    16,   nil,
   nil,    38,    38,   nil,    16,   nil,    38,   nil,   nil,    39,
    39,   nil,    38,   nil,    39,   nil,   nil,   nil,   nil,   nil,
    39,   nil,   nil,   nil,   nil,    16,    16,   nil,    16,    16,
    16,    16,    16,    38,    38,   nil,    38,    38,    38,    38,
    38,    39,    39,   nil,    39,    39,    39,    39,    39,    40,
    40,   nil,   nil,   nil,    40,   nil,   nil,    80,    80,   nil,
    40,   nil,    80,   nil,   nil,    14,    14,   nil,    80,   nil,
    14,   nil,   nil,   nil,   nil,   nil,    14,   nil,   nil,   nil,
   nil,    40,    40,   nil,    40,    40,    40,    40,    40,    80,
    80,   nil,    80,    80,    80,    80,    80,    14,    14,   nil,
    14,    14,    14,    14,    14,    79,    79,   nil,   nil,   nil,
    79,   nil,   nil,    78,    78,   nil,    79,   nil,    78,   nil,
   nil,    77,    77,   nil,    78,   nil,    77,   nil,   nil,   nil,
   nil,   nil,    77,   nil,   nil,   nil,   nil,    79,    79,   nil,
    79,    79,    79,    79,    79,    78,    78,   nil,    78,    78,
    78,    78,    78,    77,    77,   nil,    77,    77,    77,    77,
    77,    75,    75,   nil,   nil,   nil,    75,   nil,   nil,    74,
    74,   nil,    75,   nil,    74,   nil,   nil,    73,    73,   nil,
    74,   nil,    73,   nil,   nil,   nil,   nil,   nil,    73,   nil,
   nil,   nil,   nil,    75,    75,   nil,    75,    75,    75,    75,
    75,    74,    74,   nil,    74,    74,    74,    74,    74,    73,
    73,   nil,    73,    73,    73,    73,    73,    72,    72,   nil,
   nil,   nil,    72,   nil,   nil,    71,    71,   nil,    72,   nil,
    71,   nil,   nil,    70,    70,   nil,    71,   nil,    70,   nil,
   nil,   nil,   nil,   nil,    70,   nil,   nil,   nil,   nil,    72,
    72,   nil,    72,    72,    72,    72,    72,    71,    71,   nil,
    71,    71,    71,    71,    71,    70,    70,   nil,    70,    70,
    70,    70,    70,    69,    69,   nil,   nil,   nil,    69,   nil,
   nil,    68,    68,   nil,    69,   nil,    68,   nil,   nil,    63,
    63,   nil,    68,   nil,    63,   nil,   nil,   nil,   nil,   nil,
    63,   nil,   nil,   nil,   nil,    69,    69,   nil,    69,    69,
    69,    69,    69,    68,    68,   nil,    68,    68,    68,    68,
    68,    63,    63,   nil,    63,    63,    63,    63,    63,    65,
    65,   nil,   nil,   nil,    65,   nil,   nil,    66,    66,   nil,
    65,   nil,    66,   nil,   nil,    67,    67,   nil,    66,   nil,
    67,   nil,   nil,   nil,   nil,   nil,    67,   nil,   nil,   nil,
   nil,    65,    65,   nil,    65,    65,    65,    65,    65,    66,
    66,   nil,    66,    66,    66,    66,    66,    67,    67,   nil,
    67,    67,    67,    67,    67,    76,    76,   nil,   nil,   nil,
    76,   nil,   nil,   nil,   nil,   nil,    76,   nil,   141,   141,
   141,   141,   141,   141,   141,   141,   141,   141,   141,   nil,
   141,   141,   nil,   141,   nil,   nil,   nil,    76,    76,   nil,
    76,    76,    76,    76,    76,   141,   103,   103,   103,   103,
   103,   103,   103,   103,   103,   103,   103,   nil,   103,   103,
   nil,   103,   104,   104,   104,   104,   104,   104,   104,   104,
   104,   104,   104,   103,   104,   104,   nil,   104,   105,   105,
   105,   105,   105,   105,   105,   105,   105,   105,   105,   104,
   105,   105,   nil,   105,   106,   106,   106,   106,   106,   106,
   106,   106,   106,   106,   106,   105,   106,   106,   nil,   106,
    85,    85,    85,    85,    85,    85,    85,    85,    85,    85,
    85,   106,    85,    85,   nil,    85,   118,   118,   118,   118,
   118,   118,   118,   118,   118,   101,   nil,    85,   101,   101,
   101,   101,   101,   101,   101,   101,   101,   101,   101,   nil,
   101,   101,   nil,   101,   102,   102,   102,   102,   102,   102,
   102,   102,   102,   102,   102,   nil,   102,   102,   102,   102,
   124,   124,   124,   124,   124,   124,   124,   124,   124,   124,
   124,   nil,   124,   124,   nil,   124,    51,    51,    51,    51,
    51,    51,    51,    51,    51,    51,    51,   nil,    51,    51,
   nil,    51,    62,    62,    62,    62,    62,    62,    62,    62,
    62,    62,    62,   nil,    62,    62,   nil,    62,   112,   112,
   112,   112,   112,   112,   112,   112,   112,   112,   112,   nil,
   112,   112,   116,   116,   116,   116,   116,   116,   116,   116,
   116,   116,   116,   115,   115,   115,   115,   115,   115,   115,
   115,   115,   115,   115,   113,   113,   113,   113,   113,   113,
   113,   113,   113,   113,   113,   120,   120,   120,   120,   120,
   120,   120,   120,   120,   119,   119,   119,   119,   119,   119,
   119,   119,   119 ]

racc_action_pointer = [
    -6,   100,    31,    96,    66,   nil,    80,    52,    43,   nil,
   nil,   nil,   nil,   nil,   532,   nil,   460,   102,    63,   227,
   235,    36,   nil,   nil,    91,   nil,   -18,   nil,    66,   348,
   nil,    -4,   nil,    76,    52,    33,    -5,   178,   468,   476,
   516,   nil,   nil,   nil,   nil,   nil,   -15,   268,   -18,    -4,
   nil,  1026,    21,   nil,   nil,   -19,    -3,    25,    51,     6,
   106,   nil,  1042,   756,   nil,   796,   804,   812,   748,   740,
   700,   692,   684,   644,   636,   628,   852,   588,   580,   572,
   524,   420,   412,   404,    42,   950,   nil,   nil,   nil,    56,
   nil,   nil,   292,   356,   nil,     9,   nil,   nil,   nil,    28,
   nil,   978,   994,   886,   902,   918,   934,    61,    54,   nil,
   nil,   nil,  1058,  1094,    -1,  1083,  1072,   243,   966,  1114,
  1105,   -24,   nil,   -25,  1010,   nil,   145,    31,    72,   nil,
   364,   nil,   nil,   nil,   nil,   nil,   300,   nil,   308,   nil,
    53,   858,   202,   161,    94,    62,     4,    76,   100,   nil,
   -26,    -4,   nil,   nil,    89,    64,   nil ]

racc_action_default = [
   -74,   -74,   -74,   -74,   -74,    -2,   -74,    -4,   -74,   -16,
   -51,   -52,   -53,   -54,   -74,   -56,   -74,   -74,   -74,   -74,
   -74,   -74,   157,    -1,   -74,    -5,   -74,   -14,   -74,   -74,
   -17,   -18,   -19,   -74,   -74,   -74,   -74,   -74,   -74,   -74,
   -74,   -41,   -42,   -47,   -48,   -49,   -74,   -74,   -74,   -74,
   -59,   -62,   -60,   -63,   -66,   -61,   -74,    -3,   -74,   -74,
   -74,   -50,   -13,   -74,   -44,   -74,   -74,   -74,   -74,   -74,
   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,   -74,
   -74,   -74,   -74,   -74,   -74,   -74,   -31,   -36,   -55,   -74,
   -57,   -58,   -74,   -74,    -6,    -7,    -8,   -10,   -11,   -74,
   -15,   -74,   -74,   -74,   -74,   -74,   -74,   -24,   -25,   -26,
   -27,   -28,   -29,   -32,   -33,   -34,   -35,   -37,   -38,   -39,
   -40,   -68,   -30,   -72,   -64,   -65,   -74,   -74,   -74,   -43,
   -74,   -20,   -21,   -22,   -23,   -67,   -74,   -73,   -74,    -9,
   -74,   -74,   -74,   -74,   -74,   -46,   -74,   -74,   -74,   -45,
   -70,   -74,   -12,   -69,   -74,   -74,   -71 ]

racc_goto_table = [
     4,     8,    64,    25,   135,    27,   137,    61,   140,    52,
    55,    37,    46,    47,    96,    49,     8,    50,    48,    24,
    56,    57,    95,     8,   148,   125,    62,     8,     1,   nil,
   nil,   nil,   nil,   153,   nil,    85,    86,    87,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    94,   nil,    27,   nil,   100,
   101,   nil,   102,   103,   104,   105,   106,   107,   108,   109,
   110,   111,   112,   113,   114,   115,   116,   117,   118,   119,
   120,   121,   139,     8,   nil,   nil,   123,   nil,     8,   124,
   126,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   149,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   141,   nil,   nil,
   nil,   nil,   nil,   142,   nil,   143,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   150,   nil,     8,   nil,   nil,   nil,   154,
     8 ]

racc_goto_check = [
     2,    11,    16,     5,    25,    11,    25,    17,     9,    23,
    23,    12,    20,    12,     8,     2,    11,    11,    22,     3,
    11,     4,     7,    11,     9,    24,    12,    11,     1,   nil,
   nil,   nil,   nil,    25,   nil,    12,    12,    12,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     5,   nil,    11,   nil,    11,
    12,   nil,    12,    12,    12,    12,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    12,     4,     8,    11,   nil,   nil,     4,   nil,    11,    12,
    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    16,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    12,   nil,   nil,
   nil,   nil,   nil,    12,   nil,    12,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     4,   nil,    11,   nil,   nil,   nil,     2,
    11 ]

racc_goto_pointer = [
   nil,    28,    -2,    13,    -3,    -3,   nil,   -37,   -45,  -120,
   nil,    -1,    -3,   nil,   nil,   nil,   -29,   -21,   nil,   nil,
    -2,   nil,     2,   -10,   -67,  -117 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     7,   nil,    26,   nil,   nil,    41,
    11,    31,    51,    30,    32,    42,   nil,    10,    12,    13,
   nil,    15,   nil,   nil,    53,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 57, :_reduce_1,
  2, 57, :_reduce_2,
  3, 58, :_reduce_3,
  1, 58, :_reduce_4,
  1, 59, :_reduce_5,
  3, 59, :_reduce_6,
  3, 61, :_reduce_7,
  1, 63, :_reduce_none,
  3, 63, :_reduce_none,
  1, 64, :_reduce_10,
  1, 64, :_reduce_11,
  6, 64, :_reduce_none,
  3, 66, :_reduce_13,
  1, 62, :_reduce_14,
  3, 62, :_reduce_15,
  1, 67, :_reduce_16,
  1, 68, :_reduce_17,
  1, 68, :_reduce_18,
  1, 68, :_reduce_19,
  4, 68, :_reduce_20,
  4, 68, :_reduce_21,
  4, 68, :_reduce_22,
  4, 68, :_reduce_23,
  3, 68, :_reduce_24,
  3, 68, :_reduce_25,
  3, 68, :_reduce_26,
  3, 68, :_reduce_27,
  3, 68, :_reduce_28,
  3, 68, :_reduce_29,
  3, 68, :_reduce_30,
  2, 68, :_reduce_31,
  3, 68, :_reduce_32,
  3, 68, :_reduce_33,
  3, 68, :_reduce_34,
  3, 68, :_reduce_35,
  2, 68, :_reduce_36,
  3, 68, :_reduce_37,
  3, 68, :_reduce_38,
  3, 68, :_reduce_39,
  3, 68, :_reduce_40,
  1, 69, :_reduce_none,
  1, 69, :_reduce_none,
  4, 70, :_reduce_43,
  2, 70, :_reduce_44,
  6, 72, :_reduce_45,
  5, 72, :_reduce_46,
  1, 65, :_reduce_47,
  1, 71, :_reduce_48,
  1, 71, :_reduce_49,
  3, 60, :_reduce_50,
  1, 60, :_reduce_51,
  1, 73, :_reduce_52,
  1, 73, :_reduce_53,
  1, 73, :_reduce_54,
  3, 73, :_reduce_55,
  1, 73, :_reduce_56,
  3, 73, :_reduce_57,
  3, 73, :_reduce_58,
  2, 74, :_reduce_59,
  2, 75, :_reduce_60,
  2, 75, :_reduce_61,
  1, 79, :_reduce_62,
  1, 79, :_reduce_63,
  3, 79, :_reduce_64,
  3, 79, :_reduce_65,
  1, 80, :_reduce_66,
  4, 76, :_reduce_67,
  3, 76, :_reduce_68,
  5, 81, :_reduce_69,
  4, 81, :_reduce_70,
  11, 77, :_reduce_71,
  3, 78, :_reduce_72,
  4, 78, :_reduce_73 ]

racc_reduce_n = 74

racc_shift_n = 157

racc_token_table = {
  false => 0,
  :error => 1,
  "TkString" => 2,
  "TkNum" => 3,
  "TkId" => 4,
  "[" => 5,
  :right => 6,
  "]" => 7,
  "!" => 8,
  :UMINUS => 9,
  "*" => 10,
  "/" => 11,
  "%" => 12,
  "+" => 13,
  "-" => 14,
  ">=" => 15,
  "<=" => 16,
  ">" => 17,
  "<" => 18,
  "==" => 19,
  "!=" => 20,
  "||" => 21,
  "/\\" => 22,
  "\\/" => 23,
  ":" => 24,
  "," => 25,
  "|[" => 26,
  "]|" => 27,
  "declare" => 28,
  ";" => 29,
  "int" => 30,
  "bool" => 31,
  "array" => 32,
  ".." => 33,
  ":=" => 34,
  "atoi" => 35,
  "(" => 36,
  ")" => 37,
  "size" => 38,
  "min" => 39,
  "max" => 40,
  "true" => 41,
  "false" => 42,
  "if" => 43,
  "fi" => 44,
  "do" => 45,
  "od" => 46,
  "read" => 47,
  "print" => 48,
  "println" => 49,
  "-->" => 50,
  "[]" => 51,
  "for" => 52,
  "in" => 53,
  "to" => 54,
  "rof" => 55 }

racc_nt_base = 56

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"TkString\"",
  "\"TkNum\"",
  "\"TkId\"",
  "\"[\"",
  "right",
  "\"]\"",
  "\"!\"",
  "UMINUS",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "\">=\"",
  "\"<=\"",
  "\">\"",
  "\"<\"",
  "\"==\"",
  "\"!=\"",
  "\"||\"",
  "\"/\\\\\"",
  "\"\\\\/\"",
  "\":\"",
  "\",\"",
  "\"|[\"",
  "\"]|\"",
  "\"declare\"",
  "\";\"",
  "\"int\"",
  "\"bool\"",
  "\"array\"",
  "\"..\"",
  "\":=\"",
  "\"atoi\"",
  "\"(\"",
  "\")\"",
  "\"size\"",
  "\"min\"",
  "\"max\"",
  "\"true\"",
  "\"false\"",
  "\"if\"",
  "\"fi\"",
  "\"do\"",
  "\"od\"",
  "\"read\"",
  "\"print\"",
  "\"println\"",
  "\"-->\"",
  "\"[]\"",
  "\"for\"",
  "\"in\"",
  "\"to\"",
  "\"rof\"",
  "$start",
  "PROGRAMA",
  "CUERPO",
  "LISTA_DECLARACION",
  "INSTRUCCIONES",
  "DECLARACION",
  "LISTA_IDENTIFICADOR",
  "LISTA_TIPO",
  "TIPO",
  "LITERAL_NUMERO",
  "ASIGNACION",
  "IDENTIFICADOR",
  "EXPRESION",
  "LITERAL",
  "EXP_ARRAY",
  "LITERAL_BOOLEANO",
  "EXP_ARRAY_REC",
  "INSTRUCCION",
  "ENTRADA",
  "SALIDA",
  "CONDICIONAL",
  "ITERACION_FOR",
  "ITERACION_DO",
  "IMPRIMIR",
  "STRING",
  "GUARDIA" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parserGusb2.y', 40)
  def _reduce_1(val, _values, result)
     result = Programa.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 41)
  def _reduce_2(val, _values, result)
     result = Programa.new(nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 46)
  def _reduce_3(val, _values, result)
     result = Cuerpo.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 47)
  def _reduce_4(val, _values, result)
     result = Cuerpo.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 52)
  def _reduce_5(val, _values, result)
     result = ListaDeclaracion.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 53)
  def _reduce_6(val, _values, result)
     result = ListaDeclaracion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 58)
  def _reduce_7(val, _values, result)
     result = Declaracion.new(val[0],nil) 
    result
  end
.,.,

# reduce 8 omitted

# reduce 9 omitted

module_eval(<<'.,.,', 'parserGusb2.y', 67)
  def _reduce_10(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 68)
  def _reduce_11(val, _values, result)
     result = nil 
    result
  end
.,.,

# reduce 12 omitted

module_eval(<<'.,.,', 'parserGusb2.y', 74)
  def _reduce_13(val, _values, result)
     result = Asignacion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 79)
  def _reduce_14(val, _values, result)
     result = ListaId.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 80)
  def _reduce_15(val, _values, result)
     result = ListaId.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 85)
  def _reduce_16(val, _values, result)
     result = Identificador.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 90)
  def _reduce_17(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 91)
  def _reduce_18(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 92)
  def _reduce_19(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 93)
  def _reduce_20(val, _values, result)
     result = Atoi.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 94)
  def _reduce_21(val, _values, result)
     result = Size.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 95)
  def _reduce_22(val, _values, result)
     result = Min.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 96)
  def _reduce_23(val, _values, result)
     result = Max.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 97)
  def _reduce_24(val, _values, result)
    result = OpSuma.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 98)
  def _reduce_25(val, _values, result)
     result = OpResta.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 99)
  def _reduce_26(val, _values, result)
     result = OpMultiplicacion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 100)
  def _reduce_27(val, _values, result)
     result = OpDivisionE.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 101)
  def _reduce_28(val, _values, result)
     result = OpModE.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 102)
  def _reduce_29(val, _values, result)
     result = OpComa.new(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 103)
  def _reduce_30(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 104)
  def _reduce_31(val, _values, result)
     result = OpUMINUS.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 105)
  def _reduce_32(val, _values, result)
     result = OpAnd.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 106)
  def _reduce_33(val, _values, result)
     result = OpOr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 107)
  def _reduce_34(val, _values, result)
     result = OpEquivalente.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 108)
  def _reduce_35(val, _values, result)
     result = OpDesigual.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 109)
  def _reduce_36(val, _values, result)
     result = OpExclamacion.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 110)
  def _reduce_37(val, _values, result)
     result = OpMenor.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 111)
  def _reduce_38(val, _values, result)
     result = OpMenorIgual.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 112)
  def _reduce_39(val, _values, result)
     result = OpMayorIgual.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 113)
  def _reduce_40(val, _values, result)
     result = OpMayor.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 41 omitted

# reduce 42 omitted

module_eval(<<'.,.,', 'parserGusb2.y', 124)
  def _reduce_43(val, _values, result)
    result = ArrayConsult.new(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 125)
  def _reduce_44(val, _values, result)
    result = ArrayAsig.new(val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 129)
  def _reduce_45(val, _values, result)
    result = ListArrayAsig.new(nil,val[1],val[3],val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 130)
  def _reduce_46(val, _values, result)
    result = ListArrayAsig.new(nil,val[1],val[3],nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 134)
  def _reduce_47(val, _values, result)
     result = LiteralNumerico.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 139)
  def _reduce_48(val, _values, result)
     result = LiteralBooleano.new("true") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 140)
  def _reduce_49(val, _values, result)
     result = LiteralBooleano.new("false") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 145)
  def _reduce_50(val, _values, result)
     result = Instrucciones.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 146)
  def _reduce_51(val, _values, result)
     result = Instrucciones.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 152)
  def _reduce_52(val, _values, result)
     result = Instruccion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 153)
  def _reduce_53(val, _values, result)
     result = Instruccion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 154)
  def _reduce_54(val, _values, result)
     result = Instruccion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 155)
  def _reduce_55(val, _values, result)
     result = Instruccion.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 156)
  def _reduce_56(val, _values, result)
     result = Instruccion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 157)
  def _reduce_57(val, _values, result)
     result = Instruccion.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 158)
  def _reduce_58(val, _values, result)
     result = Instruccion.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 163)
  def _reduce_59(val, _values, result)
     result = Entrada.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 168)
  def _reduce_60(val, _values, result)
     result = Salida.new(val[1], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 169)
  def _reduce_61(val, _values, result)
     result = Salida.new(val[1], "SALTO") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 174)
  def _reduce_62(val, _values, result)
     result = Imprimir.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 175)
  def _reduce_63(val, _values, result)
     result = Imprimir.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 176)
  def _reduce_64(val, _values, result)
     result = Imprimir.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 177)
  def _reduce_65(val, _values, result)
     result = Imprimir.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 182)
  def _reduce_66(val, _values, result)
     result = Str.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 187)
  def _reduce_67(val, _values, result)
     result = Condicional.new(val[0],val[2],val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 188)
  def _reduce_68(val, _values, result)
     result = Condicional.new(val[0],val[2],nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 193)
  def _reduce_69(val, _values, result)
    result = Guardia.new(val[1],val[3],val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 194)
  def _reduce_70(val, _values, result)
    result = Guardia.new(val[1],val[3],nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 197)
  def _reduce_71(val, _values, result)
     result = IteradorFor.new(val[1], val[3], val[5], val[8]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 202)
  def _reduce_72(val, _values, result)
     result = IteratorDo.new(val[0],val[2],nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 203)
  def _reduce_73(val, _values, result)
     result = IteratorDo.new(val[0],val[2],val[3]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ParserGusb
